import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { usePageTitle } from "../hooks/usePageTitle";
import { api, getApiError } from "../api";
import { useAuth } from "../auth";
import { useModal } from "../components/Modal";
const schema=z.object({name:z.string().min(2,"Name must be at least 2 characters."),email:z.string().email("Enter a valid email."),phone:z.string().min(7,"Enter a valid phone number.")});type ProfileValues=z.infer<typeof schema>;
export default function Profile(){usePageTitle("Profile");const {user,updateUser}=useAuth(),{show}=useModal(),[error,setError]=useState(""),[saving,setSaving]=useState(false);const {register,handleSubmit,reset,formState:{errors}}=useForm<ProfileValues>({resolver:zodResolver(schema),defaultValues:{name:user?.name??"",email:user?.email??"",phone:user?.phone??""}});useEffect(()=>reset({name:user?.name??"",email:user?.email??"",phone:user?.phone??""}),[user,reset]);const onSubmit=async({name,phone}:ProfileValues)=>{setError("");setSaving(true);try{const {data}=await api.put("/users/me",{name,phone});updateUser(data.user);show({title:"Profile saved",message:"Your pickup contact details have been updated."});}catch(e){setError(getApiError(e));}finally{setSaving(false);}};return <section className="py-14"><div className="page-shell max-w-3xl"><p className="section-label">YOUR DETAILS</p><h1 className="mt-3 font-display text-5xl">Profile.</h1><p className="mt-4 text-[#786a76]">Keep your contact details ready for future cake orders.</p><form onSubmit={handleSubmit(onSubmit)} className="soft-card mt-8 space-y-6 p-7">{error&&<p className="error-text">{error}</p>}<div><label className="label">Full name</label><input className="input" autoComplete="name" {...register("name")}/>{errors.name&&<p className="error-text">{errors.name.message}</p>}</div><div><label className="label">Email</label><input className="input" type="email" disabled {...register("email")}/><p className="mt-2 text-xs text-[#786a76]">Email is used to sign in and cannot be changed here.</p>{errors.email&&<p className="error-text">{errors.email.message}</p>}</div><div><label className="label">Phone number</label><input className="input" type="tel" autoComplete="tel" {...register("phone")}/>{errors.phone&&<p className="error-text">{errors.phone.message}</p>}</div><button disabled={saving} className="btn-primary disabled:opacity-60">{saving?"Saving…":"Save profile"}</button></form></div></section>;}
